project:
  type: website

website:
  description: 'A blog built with Quarto'
  site-url: https://andy-weaver.github.io/
  title: 'andy-weaver'
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about.qmd
  page-navigation: true

format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: false
    code-copy: true
    code-overflow: wrap
    sanitize-html: false
